services:
  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - PROXY_GIVER_HOST=proxy-giver
    depends_on:
      - redis
      - proxy-giver
    restart: unless-stopped
    deploy:
      replicas: 3

  proxy-giver:
    build: ./proxy-giver
    container_name: proxy_giver_api
    ports:
      - "9000:9000"
    volumes:
      - ./proxy-giver:/app
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    restart: unless-stopped